### ISSUE TITLE
Nested hook execution in package "DeLorean"

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/promisedyntracer#20]
I got the following log:
```
[1/1] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/DeLorean-DeLorean.R
Loading required package: Rcpp
Error in Èèl¬U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: estimate.hyper ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning message:
In ðôðŽU :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_promise_created

```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/DeLorean-DeLorean.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, echo=F-------------------------------------------------------
    knitr::opts_chunk$set(
        fig.width=12,
        fig.height=12/1.618,
        out.width='685px',
        dpi=144,
        message=FALSE)
    
    ## ----guoData-------------------------------------------------------------
    library(DeLorean)
    library(dplyr)
    data(GuoDeLorean)
    # Limit number of cores to 2 for CRAN
    options(DL.num.cores=min(default.num.cores(), 2))
    
    ## ------------------------------------------------------------------------
    dl <- de.lorean(guo.expr, guo.gene.meta, guo.cell.meta)
    
    ## ------------------------------------------------------------------------
    dl <- estimate.hyper(
        dl,
        sigma.tau=0.5,
        length.scale=1.5,
        model.name='exact-sizes')
    
    ## ------------------------------------------------------------------------
    num.at.each.stage <- 5
    epi.sampled.cells <- guo.cell.meta %>%
        filter(capture < "32C" |
               "EPI" == cell.type |
               "ICM" == cell.type) %>%
        group_by(capture) %>%
        do(sample_n(., num.at.each.stage))
    dl <- filter_cells(dl, cells=epi.sampled.cells$cell)
    
    ## ----aov-----------------------------------------------------------------
    dl <- aov.dl(dl)
    
    ## ------------------------------------------------------------------------
    head(dl$aov)
    
    ## ------------------------------------------------------------------------
    tail(dl$aov)
    
    ## ---- exec=FALSE---------------------------------------------------------
    dl <- filter_genes(dl, genes=head(dl$aov, 20)$gene)
    
    ## ------------------------------------------------------------------------
    dl <- examine.convergence(dl)
    plot(dl, type='Rhat')
    
    ## ----plot----------------------------------------------------------------
    plot(dl, type='pseudotime')
    
    ## ------------------------------------------------------------------------
    dl <- make.predictions(dl)
    plot(dl, type='profiles')
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/DeLorean-DeLorean.OK')


```

**Comment by aviralg** [comment]
Here is the relevant portion of the `backtrace` from `gdb` -

```
#0  0x0000000000476d77 in Rf_findcontext (mask=4, env=0xceb1bc0, val=0xd38eff0) at context.c:331
#1  0x00000000004d193b in gotoExitingHandler (cond=0xa499d8, call=0xceb4740, entry=0xd244f70) at errors.c:1621
#2  0x00000000004d1b99 in vsignalError (call=0xceb4740, format=0x648055 "%s", ap=0x7ffffffb8138) at errors.c:1662
#3  0x00000000004cefeb in Rf_errorcall (call=0xceb4740, format=0x648055 "%s") at errors.c:794
#4  0x00000000004cf328 in Rf_error (format=0x7fffe0c0d240 "DYNTRACE: encountered ACTIVE BINDING frame, missing implementation, confused") at errors.c:846
#5  0x00007fffe0b434a3 in get_binding_value (frame=<optimized out>) at lookup.cpp:15
#6  get_hash (table=<optimized out>, symbol=<optimized out>, hashcode=<optimized out>) at lookup.cpp:24
#7  find_promise_in_single_environment (symbol=symbol@entry=0x38961a8, rho=rho@entry=0xca65840) at lookup.cpp:57
#8  0x00007fffe0b434fd in find_promise_in_environment (symbol=0x38961a8, rho2=rho2@entry=0xcf1c288) at lookup.cpp:78
#9  0x00007fffe0b4b188 in get_full_type_inner (sexp=0x38961a8, rho=0xcf1c288, result=std::vector of length 1, capacity 1 = {...}, visited=std::set with 1 elements = {...}) at sexptypes.cpp:160
#10 0x00007fffe0b4b4e5 in get_full_type (promise=promise@entry=0xceb0e30, result=std::vector of length 1, capacity 1 = {...}) at sexptypes.cpp:176
#11 0x00007fffe0b49c09 in create_promise_get_info (context=context@entry=0x3845380, promise=0xceb0e30, rho=<optimized out>) at recorder.cpp:303
#12 0x00007fffe0b45089 in promise_created (context=0x3845380, prom=<optimized out>, rho=<optimized out>) at probes.cpp:218
```
Its related to all the other issues of *Nested Hook Execution*.

**Comment by kondziu** [comment]
```
[1/1] Executing file: /home/kondziu/workspace/promise-dyntracing-experiment/data/2018-01-25-15-17-33/vignettes/DeLorean-DeLorean.R
Loading required package: Rcpp
DYNTRACE LOG - ERROR - lookup.cpp · get_binding_value(...) · 19 - encountered ACTIVE BINDING frame, missing implementation, confused
Warning message:
In dir.create(instrumented.code.dir) :
  '/home/kondziu/workspace/promise-dyntracing-experiment/data/2018-01-25-15-17-33/vignettes' already exists
[1/1] Done executing file: /home/kondziu/workspace/promise-dyntracing-experiment/data/2018-01-25-15-17-33/vignettes/DeLorean-DeLorean.R
```

**Comment by kondziu** [comment]
```
[2/4] Executing file: /home/kondziu/workspace/promise-dyntracing-experiment/data/2018-01-25-15-17-33/vignettes/ForecastFramework-DataPolymorphism.R
Loading required package: R6
Loading required package: lattice
DYNTRACE LOG - ERROR - lookup.cpp · get_binding_value(...) · 19 - encountered ACTIVE BINDING frame, missing implementation, confused
```
