### ISSUE TITLE
Nested hook execution in package "ForecastFramework"

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/promisedyntracer#24]
I got the following log:
```
[2/4] Executing file: /media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes/ForecastFramework-DataPolymorphism.R
Loading required package: R6
Loading required package: lattice
Error in ÈH3U : 
  [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_jump_ctxt
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> doTryCatch -> evalq -> evalq
In addition: Warning messages:
1: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
2: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
3: In  :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
4: In ÈH3U :
  '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/vignettes' already exists
error while dyntracing code block
Error: [ERROR] - [NESTED HOOK EXECUTION] - probe_promise_created triggers probe_end
Execution halted

```

The code of the vignette (including instrumentation):
```r
library(promisedyntracer)

dyntracer <- create_dyntracer('/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/ForecastFramework-DataPolymorphism.sqlite',verbose=FALSE)
dyntrace(dyntracer, {

    ## ----setup, include=FALSE------------------------------------------------
    knitr::opts_chunk$set(echo = TRUE)
    library(dplyr)
    library(ForecastFramework)
    library(DAAG)
    
    ## ------------------------------------------------------------------------
    data("Orange")
    listFormData = ObservationList$new(
      data=Orange
    )
    
    ## ------------------------------------------------------------------------
    library(DAAG)
    data("bomregions")
    matrix_data = t(bomregions[1:8,c(10:17)])
    matrixFormData = IncidenceMatrix$new(
      data=matrix_data,
      colData = list(
        yr=bomregions[1:8,1]
      )
    )
    
    ## ----Comparison, warning = FALSE,message = FALSE-------------------------
    listFormData$formArray(
      row='Tree',
      col='age',
      val='circumference'
    )
    listFormData$mat
    matrixFormData$mat
    
    ## ------------------------------------------------------------------------
    model = MoveAheadModel$new()
    model$fit(listFormData)
    model$fit(matrixFormData)
    model$predict(matrixFormData)$mean()$mat
    model$predict(listFormData)$mean()$mat
    
    ## ----Class Changing------------------------------------------------------
    anotherMatrixFormData = IncidenceMatrix$new(listFormData)
    anotherMatrixFormData$mat
    listFormData$mat
    

})
destroy_dyntracer(dyntracer)
write('OK', '/media/kondziu/b7a9548c-13a0-4fe6-8a28-de8d491a209b/R/traces/lucoa/2018-01-19-18-30-19/data/ForecastFramework-DataPolymorphism.OK')


```

**Comment by aviralg** [comment]
Here is the relevant part of the gdb backtrace -

```
#0  0x0000000000476d77 in Rf_findcontext (mask=4, env=0x860ad28, val=0xcb851b8) at context.c:331
#1  0x00000000004d193b in gotoExitingHandler (cond=0xa499d8, call=0x8612880, entry=0xc6bc808) at errors.c:1621
#2  0x00000000004d1b99 in vsignalError (call=0x8612880, format=0x648055 "%s", ap=0x7ffffffb43c8) at errors.c:1662
#3  0x00000000004cefeb in Rf_errorcall (call=0x8612880, format=0x648055 "%s") at errors.c:794
#4  0x00000000004cf328 in Rf_error (format=0x7fffe0c0d240 "DYNTRACE: encountered ACTIVE BINDING frame, missing implementation, confused") at errors.c:846
#5  0x00007fffe0b434a3 in get_binding_value (frame=<optimized out>) at lookup.cpp:15
#6  get_hash (table=<optimized out>, symbol=<optimized out>, hashcode=<optimized out>) at lookup.cpp:24
#7  find_promise_in_single_environment (symbol=symbol@entry=0x452d998, rho=rho@entry=0x8819290) at lookup.cpp:57
#8  0x00007fffe0b434fd in find_promise_in_environment (symbol=0x452d998, rho2=rho2@entry=0x877a7a8) at lookup.cpp:78
#9  0x00007fffe0b4b188 in get_full_type_inner (sexp=0x452d998, rho=0x877a7a8, result=std::vector of length 1, capacity 1 = {...}, visited=std::set with 1 elements = {...}) at sexptypes.cpp:160
#10 0x00007fffe0b4b4e5 in get_full_type (promise=promise@entry=0x86093f8, result=std::vector of length 1, capacity 1 = {...}) at sexptypes.cpp:176
#11 0x00007fffe0b49c09 in create_promise_get_info (context=context@entry=0x2343150, promise=0x86093f8, rho=<optimized out>) at recorder.cpp:303
#12 0x00007fffe0b45089 in promise_created (context=0x2343150, prom=<optimized out>, rho=<optimized out>) at probes.cpp:218
#13 0x000000000052f0e9 in Rf_mkPROMISE (expr=0x452d998, rho=0x877a7a8) at memory.c:2446
```
The reason for this hook execution should be clear from this.

**Comment by kondziu** [comment]
```
[2/4] Executing file: /home/kondziu/workspace/promise-dyntracing-experiment/data/2018-01-25-15-17-33/vignettes/ForecastFramework-DataPolymorphism.R
Loading required package: R6
Loading required package: lattice
DYNTRACE LOG - ERROR - lookup.cpp · get_binding_value(...) · 19 - encountered ACTIVE BINDING frame, missing implementation, confused
Warning messages:
```
